language: java
os: linux
dist: xenial
install:
  - jdk_switcher use openjdk8
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true
jdk:
  - openjdk7
  - openjdk8
  - oraclejdk9
  - openjdk11
script:
  - jdk_switcher use $TRAVIS_JDK_VERSION
  - ./mvnw test -Dmaven.javadoc.skip=true
