language: java
dist: trusty
os: linux
install:
  - jdk_switcher use openjdk7
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true
jdk:
  - openjdk7
  - openjdk8
  - openjdk9
script:
  - jdk_switcher use $TRAVIS_JDK_VERSION
  - ./mvnw test -Dmaven.javadoc.skip=true
